samples: config-tumor_only_ffpe/samples.tsv

units: config-tumor_only_ffpe/units.tsv

# Optional BED file with target regions
# target_regions: "raw/V5UTR.bed"

primers:
  trimming:
    activate: false
    # path to fasta files containg primer sequences
    primers_fa1: "path/to/primer-fa1"
    primers_fa2: "path/to/primer-fa2"
    # optional primer file allowing to define primers per sample
    # overwrites primers_fa1 and primers_fa2
    # the tsv file requires three fields: panel, fa1 and fa2 (optional)
    tsv: ""
    # Mean insert size between the outer primer ends.
    # If 0 or not set the bowtie default value of 250 will be used
    library_length: 0

calc_consensus_reads:
  # Set to true for merging PCR duplicates and overlapping reads using rbt:
  # https://github.com/rust-bio/rust-bio-tools
  activate: false

# Estimation of mutational burden.
mutational_burden:
  # Size of the sequenced coding genome for mutational burden estimation
  # Attention: when doing panel sequencing, set this to the
  # CAPTURED coding genome, not the entire one!
  coding_genome_size: 3e7

report:
  max_read_depth: 250
  stratify:
    # if stratification is deactivated, one tabular report for all
    # samples will be created.
    activate: false
    # select a sample sheet column for stratification, e.g. the tumorboard session
    by-column: session

params:
  varlociraptor:
    # add extra arguments for varlociraptor call
    # For example, in case of panel data consider to omit certain bias estimations
    # which might be misleading because all reads of an amplicon have the same start
    # position, strand etc. (--omit-strand-bias, --omit-read-position-bias, 
    # --omit-softclip-bias, --omit-read-orientation-bias).
    call: ""
    # Add extra arguments for varlociraptor preprocess. By default, we limit the depth to 200.
    # Increase this value for panel sequencing!
    preprocess: "--max-depth 200"
  freebayes:
    min_alternate_fraction: 0.01 # Reduce for calling variants with lower VAFs
